'use client';

import { useMemo, useState } from 'react';
import { AlertTriangle, ArrowLeft, Bell, Building2, CalendarClock, Check, CheckCircle2, ChevronRight, CircleDot, ClipboardCheck, Clock3, FileImage, FileText, Filter, Headphones, History, LayoutDashboard, MapPin, Menu, MessageSquareText, Paperclip, Phone, Search, Send, Settings, ShieldAlert, TimerReset, UserRound, Users, Wrench, XCircle } from 'lucide-react';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Requirement = { name: string; done: boolean; detail: string };
type Ticket = {
  id: string; title: string; store: string; city: string; group: string; analyst: string; technician: string;
  status: 'Em campo' | 'Aguardando evidencias' | 'Em validacao' | 'Pendente tecnico'; priority: 'Critica' | 'Alta' | 'Media';
  sla: string; updated: string; description: string; requirements: Requirement[];
};

const initialTickets: Ticket[] = [
  { id: 'FSA-129617', title: 'Impressora Zebra nao calibra', store: 'L1389 · Maracanau', city: 'Maracanau, CE', group: 'N1 Nordeste', analyst: 'Ana Beatriz', technician: 'Demostenes Pedrosa', status: 'Aguardando evidencias', priority: 'Critica', sla: '42 min', updated: 'Ha 8 min', description: 'Tecnico concluiu limpeza e ajuste do sensor. Chamado aguarda documentacao para validacao.', requirements: [{ name: 'Check-in no local', done: true, detail: 'Registrado 13:42' }, { name: 'Fotos antes do atendimento', done: true, detail: '3 arquivos anexados' }, { name: 'Fotos depois do atendimento', done: false, detail: 'Obrigatorio: equipamento funcionando' }, { name: 'RAT assinada', done: false, detail: 'Aguardando assinatura do gerente' }, { name: 'Teste de impressao', done: true, detail: 'Cupom de teste anexado' }] },
  { id: 'FSA-129461', title: 'CPU PDV 301 com travamento', store: 'L5321 · Sao Jose de Mipibu', city: 'Sao Jose de Mipibu, RN', group: 'N1 Nordeste', analyst: 'Ana Beatriz', technician: 'Lucas Andrade', status: 'Em campo', priority: 'Alta', sla: '1h 18m', updated: 'Ha 3 min', description: 'Tecnico em diagnostico de memoria e armazenamento do PDV 301.', requirements: [{ name: 'Check-in no local', done: true, detail: 'Registrado 14:08' }, { name: 'Foto do serial', done: true, detail: '1 arquivo anexado' }, { name: 'Diagnostico tecnico', done: false, detail: 'Preencher causa raiz' }, { name: 'RAT assinada', done: false, detail: 'Disponivel apos conclusao' }, { name: 'Check-out', done: false, detail: 'Pendente' }] },
  { id: 'FSA-129426', title: 'Desktop nao inicia', store: 'L1075 · Itabira', city: 'Itabira, MG', group: 'N1 Sudeste', analyst: 'Bruno Costa', technician: 'Marcos Souza', status: 'Em validacao', priority: 'Alta', sla: '2h 05m', updated: 'Ha 12 min', description: 'Troca de fonte concluida e equipamento inicializando normalmente.', requirements: [{ name: 'Check-in no local', done: true, detail: 'Registrado 11:20' }, { name: 'Fotos antes e depois', done: true, detail: '6 arquivos anexados' }, { name: 'RAT assinada', done: true, detail: 'Assinada por Carlos Lima' }, { name: 'Numero de serie da peca', done: true, detail: 'Fonte CX-88219' }, { name: 'Check-out', done: true, detail: 'Registrado 13:55' }] },
  { id: 'FSA-129311', title: 'Hydra parado em carregando', store: 'L1047 · Caninde', city: 'Caninde, CE', group: 'N1 Nordeste', analyst: 'Carlos Nunes', technician: 'Rafael Santos', status: 'Pendente tecnico', priority: 'Media', sla: '3h 22m', updated: 'Ha 28 min', description: 'Atendimento pausado; analista solicitou captura do erro e teste de conectividade.', requirements: [{ name: 'Check-in no local', done: true, detail: 'Registrado 10:14' }, { name: 'Print do erro Hydra', done: false, detail: 'Solicitado ao tecnico' }, { name: 'Teste de rede', done: false, detail: 'Anexar resultado do ping' }, { name: 'RAT assinada', done: false, detail: 'Pendente' }] },
  { id: 'FSA-129173', title: 'Impressora termica com falha', store: 'L1166 · Shopping Jardim Norte', city: 'Juiz de Fora, MG', group: 'N1 Sudeste', analyst: 'Bruno Costa', technician: 'Bruno Oliveira', status: 'Aguardando evidencias', priority: 'Media', sla: '4h 10m', updated: 'Ha 35 min', description: 'Manutencao finalizada; faltam documentos para encerrar o chamado.', requirements: [{ name: 'Check-in no local', done: true, detail: 'Registrado 09:05' }, { name: 'Fotos antes do atendimento', done: false, detail: 'Nao anexado' }, { name: 'Foto do teste final', done: false, detail: 'Nao anexado' }, { name: 'RAT assinada', done: true, detail: 'Assinada por Joana Alves' }] },
];

const statusColor: Record<Ticket['status'], string> = {
  'Em campo': 'border-emerald-400/25 bg-emerald-400/10 text-emerald-300',
  'Aguardando evidencias': 'border-amber-400/25 bg-amber-400/10 text-amber-300',
  'Em validacao': 'border-blue-400/25 bg-blue-400/10 text-blue-300',
  'Pendente tecnico': 'border-violet-400/25 bg-violet-400/10 text-violet-300',
};

export default function CentralN1Page() {
  const [selectedId, setSelectedId] = useState(initialTickets[0].id);
  const [query, setQuery] = useState('');
  const [group, setGroup] = useState('Todos');
  const [menu, setMenu] = useState(false);
  const [completed, setCompleted] = useState<Record<string, string[]>>({});
  const [notice, setNotice] = useState('');
  const selected = initialTickets.find((ticket) => ticket.id === selectedId) ?? initialTickets[0];
  const rows = useMemo(() => initialTickets.filter((ticket) => {
    const matchesGroup = group === 'Todos' || ticket.group === group;
    const q = query.toLowerCase();
    return matchesGroup && [ticket.id, ticket.title, ticket.store, ticket.technician, ticket.analyst].some((value) => value.toLowerCase().includes(q));
  }), [query, group]);
  const requirements = selected.requirements.map((item) => ({ ...item, done: item.done || (completed[selected.id] ?? []).includes(item.name) }));
  const missing = requirements.filter((item) => !item.done).length;

  function toggleRequirement(name: string) {
    setCompleted((current) => {
      const list = current[selected.id] ?? [];
      return { ...current, [selected.id]: list.includes(name) ? list.filter((item) => item !== name) : [...list, name] };
    });
  }

  return <main className="min-h-screen bg-background text-foreground">
    <aside className={`fixed inset-y-0 left-0 z-40 w-[252px] border-r border-sidebar-border bg-sidebar px-4 py-5 transition-transform lg:translate-x-0 ${menu ? 'translate-x-0' : '-translate-x-full'}`}>
      <a href="/" className="flex h-12 items-center gap-3 px-2"><div className="grid size-10 place-items-center rounded-xl bg-primary text-lg font-black text-primary-foreground shadow-[0_8px_28px_rgba(229,98,35,.25)]">C</div><div><div className="text-[15px] font-extrabold tracking-tight">Caju OS</div><div className="text-[10px] font-semibold uppercase tracking-[.16em] text-muted-foreground">Central de operacoes</div></div></a>
      <nav className="mt-8 space-y-1"><p className="mb-3 px-3 text-[10px] font-bold uppercase tracking-[.15em] text-muted-foreground">Atendimento N1</p><a href="/" className="flex h-10 items-center gap-3 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><LayoutDashboard className="size-[18px]" />Visao geral</a><button className="flex h-10 w-full items-center gap-3 rounded-lg bg-sidebar-accent px-3 text-sm font-medium shadow-[inset_3px_0_0_var(--primary)]"><Headphones className="size-[18px] text-primary" />Minha fila</button><button className="flex h-10 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><Users className="size-[18px]" />Grupos N1</button><button className="flex h-10 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><ClipboardCheck className="size-[18px]" />Validacoes</button><button className="flex h-10 w-full items-center gap-3 rounded-lg px-3 text-sm font-medium text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><History className="size-[18px]" />Historico</button></nav>
      <div className="mt-8 rounded-xl border border-amber-400/20 bg-amber-400/8 p-4"><div className="flex items-center gap-2 text-xs font-bold text-amber-300"><ShieldAlert className="size-4" />Atencao da equipe</div><p className="mt-2 text-[11px] leading-relaxed text-muted-foreground">7 chamados estao com documentacao incompleta e 3 proximos do SLA.</p></div>
      <div className="absolute inset-x-4 bottom-5 border-t border-sidebar-border pt-4"><button className="flex h-10 w-full items-center gap-3 rounded-lg px-3 text-sm text-muted-foreground hover:bg-sidebar-accent hover:text-foreground"><Settings className="size-[18px]" />Configuracoes</button><div className="mt-3 flex items-center gap-3 rounded-xl border border-sidebar-border bg-background/40 p-3"><div className="grid size-9 place-items-center rounded-full bg-[#28344a] text-xs font-bold text-[#9fb4d5]">AB</div><div><p className="text-xs font-semibold">Ana Beatriz</p><p className="text-[10px] text-muted-foreground">Analista N1</p></div></div></div>
    </aside>
    {menu && <button aria-label="Fechar menu" className="fixed inset-0 z-30 bg-black/60 lg:hidden" onClick={() => setMenu(false)} />}
    <section className="min-h-screen lg:pl-[252px]">
      <header className="sticky top-0 z-20 flex h-[68px] items-center gap-3 border-b border-border bg-background/90 px-4 backdrop-blur-xl sm:px-6 lg:px-8"><Button variant="ghost" size="icon" className="lg:hidden" onClick={() => setMenu(true)}><Menu /></Button><a href="/" className="hidden items-center gap-2 text-xs text-muted-foreground hover:text-foreground sm:flex"><ArrowLeft className="size-4" />Operacao</a><div className="ml-auto flex items-center gap-2"><div className="hidden items-center gap-2 rounded-full border border-emerald-400/20 bg-emerald-400/8 px-3 py-1.5 text-xs font-semibold text-emerald-300 sm:flex"><span className="size-1.5 rounded-full bg-emerald-400" />N1 online · 8 analistas</div><Button variant="ghost" size="icon"><Bell /></Button></div></header>
      <div className="mx-auto max-w-[1700px] px-4 py-6 sm:px-6 lg:px-8">
        <div><p className="mb-1 text-xs font-bold uppercase tracking-[.14em] text-primary">Atendimento e qualidade</p><h1 className="text-2xl font-extrabold tracking-[-.03em] sm:text-3xl">Central de Analistas e N1</h1><p className="mt-1 text-sm text-muted-foreground">Acompanhe o atendimento, cobre pendencias e valide a documentacao.</p></div>
        <div className="mt-6 grid grid-cols-2 gap-3 xl:grid-cols-4"><Summary label="Na minha fila" value="18" note="5 atualizados agora" icon={Headphones} color="text-blue-300" /><Summary label="Em campo" value="9" note="2 sem retorno ha 30 min" icon={Wrench} color="text-emerald-300" /><Summary label="Documentacao faltando" value="7" note="RAT ou evidencias" icon={FileText} color="text-amber-300" /><Summary label="SLA em risco" value="3" note="Menos de 1 hora" icon={TimerReset} color="text-red-300" /></div>
        <div className="mt-6 grid min-h-[680px] gap-4 xl:grid-cols-[minmax(420px,.9fr)_minmax(560px,1.35fr)]">
          <section className="overflow-hidden rounded-xl border border-border bg-card shadow-[0_12px_40px_rgba(0,0,0,.08)]"><div className="border-b border-border p-4"><div className="flex items-center gap-2"><div className="relative flex-1"><Search className="absolute left-3 top-1/2 size-4 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Buscar chamado, tecnico ou loja..." className="pl-9" /></div><Button variant="outline" size="icon"><Filter /></Button></div><div className="mt-3 flex flex-wrap gap-2">{['Todos', 'N1 Nordeste', 'N1 Sudeste'].map((item) => <Button key={item} size="sm" variant={group === item ? 'secondary' : 'ghost'} onClick={() => setGroup(item)}>{item}</Button>)}</div></div><div className="max-h-[610px] overflow-y-auto">{rows.map((ticket) => { const pending = ticket.requirements.filter((item) => !item.done).length; return <button key={ticket.id} onClick={() => { setSelectedId(ticket.id); setNotice(''); }} className={`w-full border-b border-border p-4 text-left transition last:border-0 ${selected.id === ticket.id ? 'bg-primary/8 shadow-[inset_3px_0_0_var(--primary)]' : 'hover:bg-muted/40'}`}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-2"><span className="font-mono text-xs font-bold text-primary">{ticket.id}</span><Badge variant="outline" className={ticket.priority === 'Critica' ? 'border-red-400/30 bg-red-400/10 text-red-300' : 'text-muted-foreground'}>{ticket.priority}</Badge></div><span className="flex items-center gap-1 text-[10px] text-muted-foreground"><Clock3 className="size-3" />{ticket.sla}</span></div><h3 className="mt-2 text-sm font-bold">{ticket.title}</h3><p className="mt-1 text-[11px] text-muted-foreground">{ticket.store} · {ticket.city}</p><div className="mt-3 flex items-center justify-between gap-2"><Badge variant="outline" className={statusColor[ticket.status]}>{ticket.status}</Badge>{pending > 0 ? <span className="flex items-center gap-1 text-[10px] font-bold text-amber-300"><AlertTriangle className="size-3" />{pending} pendencias</span> : <span className="flex items-center gap-1 text-[10px] font-bold text-emerald-300"><CheckCircle2 className="size-3" />Completo</span>}</div></button>})}{!rows.length && <div className="grid h-48 place-items-center text-sm text-muted-foreground">Nenhum chamado encontrado.</div>}</div></section>
          <section className="overflow-hidden rounded-xl border border-border bg-card shadow-[0_12px_40px_rgba(0,0,0,.08)]">
            <div className="border-b border-border p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex items-center gap-2"><span className="font-mono text-sm font-extrabold text-primary">{selected.id}</span><Badge variant="outline" className={statusColor[selected.status]}>{selected.status}</Badge></div><h2 className="mt-2 text-xl font-extrabold tracking-tight">{selected.title}</h2><p className="mt-1 flex items-center gap-1.5 text-xs text-muted-foreground"><MapPin className="size-3.5" />{selected.store} · {selected.city}</p></div><div className="text-right"><p className="text-[10px] uppercase tracking-wider text-muted-foreground">SLA restante</p><p className={`mt-1 font-mono text-xl font-extrabold ${selected.priority === 'Critica' ? 'text-red-300' : 'text-amber-300'}`}>{selected.sla}</p><p className="text-[10px] text-muted-foreground">Atualizado {selected.updated.toLowerCase()}</p></div></div></div>
            <div className="grid gap-5 p-5 2xl:grid-cols-[1fr_320px]">
              <div className="space-y-5"><div className="rounded-lg border border-border bg-muted/20 p-4"><h3 className="text-xs font-bold uppercase tracking-[.08em] text-muted-foreground">Resumo do atendimento</h3><p className="mt-2 text-sm leading-relaxed">{selected.description}</p></div><div><div className="mb-3 flex items-center justify-between"><div><h3 className="text-sm font-bold">Checklist de validacao</h3><p className="text-[11px] text-muted-foreground">Documentos e evidencias obrigatorias</p></div><Badge variant="outline" className={missing ? 'border-amber-400/25 text-amber-300' : 'border-emerald-400/25 text-emerald-300'}>{missing ? `${missing} faltando` : 'Completo'}</Badge></div><div className="space-y-2">{requirements.map((item) => <button key={item.name} onClick={() => toggleRequirement(item.name)} className={`flex w-full items-start gap-3 rounded-lg border p-3 text-left transition ${item.done ? 'border-emerald-400/15 bg-emerald-400/5' : 'border-amber-400/20 bg-amber-400/5 hover:border-amber-400/40'}`}><span className={`mt-0.5 grid size-5 shrink-0 place-items-center rounded-md border ${item.done ? 'border-emerald-400 bg-emerald-400 text-[#10221c]' : 'border-amber-400/50'}`}>{item.done && <Check className="size-3.5" />}</span><span className="flex-1"><span className={`block text-xs font-bold ${item.done ? '' : 'text-amber-200'}`}>{item.name}</span><span className="mt-0.5 block text-[10px] text-muted-foreground">{item.detail}</span></span>{item.done ? <CheckCircle2 className="size-4 text-emerald-300" /> : <XCircle className="size-4 text-amber-300" />}</button>)}</div></div><div><h3 className="mb-3 text-sm font-bold">Evidencias anexadas</h3><div className="grid grid-cols-2 gap-2 sm:grid-cols-3">{['Antes · frente', 'Serial equipamento', 'Cupom de teste'].map((name, index) => <div key={name} className="rounded-lg border border-border bg-muted/20 p-3"><div className="grid h-14 place-items-center rounded-md bg-background/60"><FileImage className="size-6 text-muted-foreground" /></div><p className="mt-2 truncate text-[10px] font-semibold">{name}</p><p className="text-[9px] text-muted-foreground">foto_0{index + 1}.jpg</p></div>)}<button className="grid min-h-24 place-items-center rounded-lg border border-dashed border-border text-[10px] text-muted-foreground hover:border-primary/40 hover:text-primary"><span className="text-center"><Paperclip className="mx-auto mb-1 size-5" />Adicionar arquivo</span></button></div></div></div>
              <aside className="space-y-4"><InfoCard title="Equipe do chamado"><InfoRow icon={UserRound} label="Tecnico de campo" value={selected.technician} /><InfoRow icon={Headphones} label="Analista responsavel" value={selected.analyst} /><InfoRow icon={Users} label="Grupo" value={selected.group} /></InfoCard><InfoCard title="Linha do tempo"><Timeline done title="Check-in confirmado" time="13:42" /><Timeline done title="Atendimento iniciado" time="13:55" /><Timeline title="Evidencias enviadas" time="Pendente" /><Timeline title="Validacao N1" time="Pendente" /></InfoCard><div className="rounded-xl border border-border p-4"><h3 className="text-xs font-bold">Acoes do analista</h3><div className="mt-3 grid gap-2"><Button variant="outline" onClick={() => setNotice('Mensagem de cobranca preparada para o tecnico.')}><MessageSquareText />Cobrar pendencias</Button><Button variant="outline"><Phone />Falar com tecnico</Button><Button disabled={missing > 0} onClick={() => setNotice('Atendimento validado com sucesso.')}><ClipboardCheck />Validar atendimento</Button><Button variant="destructive" onClick={() => setNotice('Chamado devolvido para correcao.')}><Send />Devolver para correcao</Button></div>{notice && <div className="mt-3 rounded-lg border border-blue-400/20 bg-blue-400/8 p-3 text-[11px] text-blue-200">{notice}</div>}</div></aside>
            </div>
          </section>
        </div>
      </div>
    </section>
  </main>;
}

function Summary({ label, value, note, icon: Icon, color }: { label: string; value: string; note: string; icon: typeof Headphones; color: string }) { return <article className="rounded-xl border border-border bg-card p-4 shadow-[0_12px_40px_rgba(0,0,0,.08)]"><div className="flex items-start justify-between"><div><p className="text-xs text-muted-foreground">{label}</p><p className="mt-2 text-2xl font-extrabold">{value}</p></div><div className={`grid size-9 place-items-center rounded-lg bg-muted ${color}`}><Icon className="size-[18px]" /></div></div><p className="mt-3 text-[11px] text-muted-foreground">{note}</p></article> }
function InfoCard({ title, children }: { title: string; children: React.ReactNode }) { return <div className="rounded-xl border border-border p-4"><h3 className="mb-3 text-xs font-bold">{title}</h3><div className="space-y-3">{children}</div></div> }
function InfoRow({ icon: Icon, label, value }: { icon: typeof UserRound; label: string; value: string }) { return <div className="flex items-center gap-2"><div className="grid size-8 place-items-center rounded-lg bg-muted text-muted-foreground"><Icon className="size-4" /></div><div className="min-w-0"><p className="text-[9px] uppercase tracking-wider text-muted-foreground">{label}</p><p className="truncate text-[11px] font-bold">{value}</p></div></div> }
function Timeline({ done, title, time }: { done?: boolean; title: string; time: string }) { return <div className="flex gap-3"><div className={`mt-0.5 grid size-5 place-items-center rounded-full border ${done ? 'border-emerald-400 bg-emerald-400/15 text-emerald-300' : 'border-border text-muted-foreground'}`}>{done ? <Check className="size-3" /> : <CircleDot className="size-3" />}</div><div><p className="text-[11px] font-semibold">{title}</p><p className="text-[9px] text-muted-foreground">{time}</p></div></div> }
