[package]
name = "caju-os-desktop"
version = "0.1.13"
description = "Caju OS desktop"
authors = ["Caju OS"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["image-png"] }
tauri-plugin-notification = "^2"
base64 = "0.22"
serde = { version = "1", features = ["derive"] }
windows-sys = { version = "0.61", features = ["Win32_Foundation", "Win32_System_DataExchange", "Win32_UI_Shell"] }
url = "2"

[features]
custom-protocol = ["tauri/custom-protocol"]
default = ["custom-protocol"]
