-- Improdutiva vira uma categoria de leitura, ao lado de atuação e evidência.
--
-- Antes a tela mostrava o valor de cada grupo já com o desconto aplicado e,
-- embaixo, uma linha de desconto informativa. Quem lia de cima para baixo
-- subtraía duas vezes e estranhava o total. Agora são três linhas que somam:
-- o que as atuações resolvidas renderam, o que as evidências resolvidas
-- renderam, e o que as improdutivas renderam (metade do que valeriam).
--
-- Por isso servicos_cents e evidencias_cents passam a guardar só a parte
-- produtiva. A tabela está vazia, então não há o que converter.
ALTER TABLE `fsa_payouts` ADD `improdutivas_cents` integer DEFAULT 0 NOT NULL;
