'use client';

import { useEffect, useMemo, useState } from 'react';
import { CalendarClock, CheckCircle2, CircleDollarSign, Loader2, PackageOpen, Save, Store, Wrench } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';

type Technician = { id: number; name: string; city: string; state: string };
type Props = { open: boolean; ticket: { id: string; title: string; store: string; city: string; rawStatus?: string }; role: string | null; user: { getIdToken: () => Promise<string> } | null; onOpenChange: (open: boolean) => void; onArchived: (ticketKey: string) => void };
type Form = Record<string, string | number | boolean | null>;
const statuses = [['triage', 'Triagem'], ['scheduling', 'Pendente de agendamento'], ['scheduled', 'Agendado'], ['operational_preparation', 'Preparação operacional'], ['in_service', 'Técnico em campo'], ['technical_pending', 'Pendência técnica'], ['validated', 'Validado'], ['awaiting_approval', 'Aguardando aprovação'], ['awaiting_spare', 'Aguardando spare'], ['spare_validated', 'Spare validado'], ['awaiting_payment', 'Aguardando pagamento'], ['resolved', 'Resolvido'], ['cancelled', 'Cancelado']];
const purchaseStatuses = ['Agendado', 'Cancelado', 'Comprado', 'Delfia', 'Direcionado', 'Encerrado', 'Enviado', 'Fechado', 'Finalizado', 'Indisponível', 'Parceiro Delfia', 'Pendente', 'Recebido', 'Reenviado'];
const initial = (ticket: Props['ticket']): Form => ({ ticketKey: ticket.id, storeCode: ticket.store.replace(/^Código da loja:\s*/i, ''), storeName: '', city: ticket.city, status: localStatus(ticket.rawStatus), openedAt: new Date().toISOString().slice(0, 16), technicianId: null, scheduledAt: '', expectedReturnAt: '', clientValueCents: null, payoutCents: null, partsValueCents: null, partsSaleCents: null, paidValueCents: null, spareSource: '', purchaseStatus: '', validationStatus: '', paymentDate: '', identifiedProblem: '', testsPerformed: '', partToReplace: '' });

export function OperationWorkflowDialog({ open, ticket, role, user, onOpenChange, onArchived }: Props) {
  const [form, setForm] = useState<Form>(() => initial(ticket));
  const [visits, setVisits] = useState<Array<{ id: number; visitNumber: number; scheduledAt: string | null; expectedReturnAt: string | null; status: string; note: string | null }>>([]);
  const [technicians, setTechnicians] = useState<Technician[]>([]);
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [message, setMessage] = useState('');
  const [technicianQuery, setTechnicianQuery] = useState('');
  const financial = role === 'gerencia';
  const set = (key: string, value: Form[string]) => setForm((current) => ({ ...current, [key]: value }));
  const money = (key: string) => ({ value: typeof form[key] === 'number' && form[key] !== null ? String(Number(form[key]) / 100) : '', onChange: (event: React.ChangeEvent<HTMLInputElement>) => set(key, moneyToCents(event.target.value)), inputMode: 'decimal' as const });

  useEffect(() => {
    if (!open || !user) return;
    let live = true; setLoading(true); setMessage(''); setTechnicianQuery(''); setForm(initial(ticket)); setVisits([]);
    void user.getIdToken().then(async (token) => {
      const headers = { Authorization: `Bearer ${token}` };
      const [operationResponse, techniciansResponse] = await Promise.all([fetch(`/api/operations?ticket=${encodeURIComponent(ticket.id)}`, { headers }), fetch('/api/technicians', { headers })]);
      const operation = await operationResponse.json() as { workflow?: Form | null; visits?: typeof visits; store?: Form | null; error?: string };
      const techPayload = await techniciansResponse.json() as { technicians?: Technician[] };
      if (!operationResponse.ok) throw new Error(operation.error || 'Falha ao carregar operação.');
      if (live) { setForm({ ...initial(ticket), ...(operation.workflow ?? {}), ...(operation.store ?? {}) }); setVisits(operation.visits ?? []); setTechnicians(techPayload.technicians ?? []); }
    }).catch((error: unknown) => { if (live) setMessage(error instanceof Error ? error.message : 'Falha ao carregar operação.'); }).finally(() => { if (live) setLoading(false); });
    return () => { live = false; };
  }, [open, ticket, user]);

  async function lookupStore() {
    if (!user || !String(form.storeCode ?? '').trim()) return;
    try { const token = await user.getIdToken(); const response = await fetch(`/api/operations?storeCode=${encodeURIComponent(String(form.storeCode))}`, { method: 'POST', headers: { Authorization: `Bearer ${token}` } }); const payload = await response.json() as { store?: Form | null }; if (payload.store) setForm((current) => ({ ...current, ...payload.store })); else setMessage('Loja não cadastrada. Preencha dados abaixo para criar.'); } catch { setMessage('Não foi possível consultar loja.'); }
  }
  async function save(addVisit = false, confirmPayment = false) {
    if (!user) return; setSaving(true); setMessage('');
    try {
      const token = await user.getIdToken();
      const payload = { ...form, technicianId: Number(form.technicianId) || null, scheduledAt: toIso(form.scheduledAt), expectedReturnAt: toIso(form.expectedReturnAt), openedAt: toIso(form.openedAt), paymentDate: toIso(form.paymentDate), addVisit, confirmPayment };
      const response = await fetch('/api/operations', { method: 'PUT', headers: { Authorization: `Bearer ${token}`, 'Content-Type': 'application/json' }, body: JSON.stringify(payload) });
      const data = await response.json() as { workflow?: Form; visits?: typeof visits; error?: string };
      if (!response.ok) throw new Error(data.error || 'Falha ao salvar operação.');
      if (data.workflow) setForm((current) => ({ ...current, ...data.workflow })); setVisits(data.visits ?? []); setMessage(confirmPayment ? 'Pagamento confirmado. Chamado arquivado.' : addVisit ? 'Nova visita adicionada ao histórico.' : 'Operação salva.'); if (confirmPayment) onArchived(ticket.id);
    } catch (error) { setMessage(error instanceof Error ? error.message : 'Falha ao salvar operação.'); } finally { setSaving(false); }
  }
  const technicianOptions = useMemo(() => {
    const query = technicianQuery.trim().toLocaleLowerCase('pt-BR');
    const unique = Array.from(new Map(technicians.map((tech) => [`${tech.name.trim().toLocaleLowerCase('pt-BR')}|${tech.city.trim().toLocaleLowerCase('pt-BR')}|${tech.state}`, tech])).values());
    return unique.filter((tech) => !query || `${tech.name} ${tech.city} ${tech.state}`.toLocaleLowerCase('pt-BR').includes(query)).map((tech) => <option key={tech.id} value={tech.id}>{tech.name} · {tech.city}/{tech.state}</option>);
  }, [technicianQuery, technicians]);
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="flex max-h-[92vh] flex-col overflow-hidden sm:max-w-4xl"><DialogHeader><DialogTitle className="flex items-center gap-2"><Wrench className="size-5 text-primary" /> Gestão operacional · {ticket.id}</DialogTitle><DialogDescription>Caju e Jira sincronizados.</DialogDescription></DialogHeader>{loading ? <div className="grid min-h-52 place-items-center"><Loader2 className="animate-spin text-primary" /></div> : <div className="min-h-0 space-y-5 overflow-y-auto pr-1"><section className="sticky top-0 z-10 grid gap-3 rounded-xl border border-primary/25 bg-background/95 p-4 shadow-lg backdrop-blur-xl sm:grid-cols-3"><Field label="Etapa"><select value={String(form.status ?? 'triage')} onChange={(event) => set('status', event.target.value)} className="field">{statuses.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></Field><Field label="Data/hora abertura"><Input type="datetime-local" value={dateField(form.openedAt)} onChange={(event) => set('openedAt', event.target.value)} /></Field><Field label="Categoria/problema"><Input value={String(form.category ?? '')} onChange={(event) => set('category', event.target.value)} placeholder="Ex.: hardware, PDV" /></Field><Field label="Técnico"><div className="space-y-2"><Input type="search" value={technicianQuery} onChange={(event) => setTechnicianQuery(event.target.value)} placeholder="Pesquisar por nome ou cidade" aria-label="Pesquisar técnico" /><select value={String(form.technicianId ?? '')} onChange={(event) => set('technicianId', Number(event.target.value) || null)} className="field"><option value="">Selecionar técnico</option>{technicianOptions}</select></div></Field><Field label="Agendamento"><Input type="datetime-local" value={dateField(form.scheduledAt)} onChange={(event) => set('scheduledAt', event.target.value)} /></Field><Field label="Retorno previsto"><Input type="datetime-local" value={dateField(form.expectedReturnAt)} onChange={(event) => set('expectedReturnAt', event.target.value)} /></Field></section>
      <Section icon={Store} title="Loja e solicitantes"><div className="grid gap-3 sm:grid-cols-3"><Field label="Código da loja"><div className="flex gap-2"><Input value={String(form.storeCode ?? '')} onChange={(event) => set('storeCode', event.target.value)} /><Button type="button" variant="outline" onClick={() => void lookupStore()}>Buscar</Button></div></Field><Field label="Nome"><Input value={String(form.storeName ?? '')} onChange={(event) => set('storeName', event.target.value)} /></Field><Field label="PDV"><Input value={String(form.pdvNumber ?? '')} onChange={(event) => set('pdvNumber', event.target.value)} /></Field><Field label="Endereço completo"><Input value={String(form.address ?? '')} onChange={(event) => set('address', event.target.value)} /></Field><Field label="Cidade"><Input value={String(form.city ?? '')} onChange={(event) => set('city', event.target.value)} /></Field><Field label="UF"><Input value={String(form.state ?? '')} onChange={(event) => set('state', event.target.value.toUpperCase())} maxLength={2} /></Field><Field label="Solicitante"><Input value={String(form.requesterName ?? '')} onChange={(event) => set('requesterName', event.target.value)} /></Field><Field label="Telefone"><Input value={String(form.requesterPhone ?? '')} onChange={(event) => set('requesterPhone', event.target.value)} /></Field><Field label="Cargo"><Input value={String(form.requesterRole ?? '')} onChange={(event) => set('requesterRole', event.target.value)} /></Field><Field label="2º solicitante"><Input value={String(form.secondaryName ?? '')} onChange={(event) => set('secondaryName', event.target.value)} /></Field><Field label="Telefone 2"><Input value={String(form.secondaryPhone ?? '')} onChange={(event) => set('secondaryPhone', event.target.value)} /></Field><Field label="Cargo 2"><Input value={String(form.secondaryRole ?? '')} onChange={(event) => set('secondaryRole', event.target.value)} /></Field></div></Section>
      <Section icon={PackageOpen} title="Spare, aprovação e segunda visita"><div className="grid gap-3 sm:grid-cols-3"><Field label="Validação"><select value={String(form.validationStatus ?? '')} onChange={(event) => set('validationStatus', event.target.value)} className="field"><option value="">Não informado</option><option>Em validação</option><option>Aprovado</option><option>Direcionado</option><option>Resolvido</option></select></Field><Field label="Origem spare"><select value={String(form.spareSource ?? '')} onChange={(event) => set('spareSource', event.target.value)} className="field"><option value="">Não informado</option><option>Delfia</option><option>Caju</option></select></Field><Field label="Status da compra"><select value={String(form.purchaseStatus ?? '')} onChange={(event) => set('purchaseStatus', event.target.value)} className="field"><option value="">Não informado</option>{purchaseStatuses.map((item) => <option key={item}>{item}</option>)}</select></Field><Field label="Status spare"><Input value={String(form.spareStatus ?? '')} onChange={(event) => set('spareStatus', event.target.value)} placeholder="Ex.: recebido, enviado" /></Field><Field label="Valor peças" disabled={!financial}><Input disabled={!financial} {...money('partsValueCents')} placeholder="0,00" /></Field><Field label="Venda peças" disabled={!financial}><Input disabled={!financial} {...money('partsSaleCents')} placeholder="0,00" /></Field></div><div className="mt-3 flex flex-wrap gap-2"><Button type="button" variant="outline" onClick={() => void save(true)} disabled={saving}><CalendarClock /> Adicionar visita/retorno</Button>{visits.map((visit) => <span key={visit.id} className="rounded-lg border border-border px-3 py-2 text-xs">Visita {visit.visitNumber} · {visit.scheduledAt ? new Date(visit.scheduledAt).toLocaleString('pt-BR') : 'a definir'}</span>)}</div></Section>
      <Section icon={CircleDollarSign} title="Valores e pagamento"><div className="grid gap-3 sm:grid-cols-3"><Field label="Valor recebido" disabled={!financial}><Input disabled={!financial} {...money('clientValueCents')} placeholder="0,00" /></Field><Field label="Repasse técnico" disabled={!financial}><Input disabled={!financial} {...money('payoutCents')} placeholder="0,00" /></Field><Field label="Data pagamento" disabled={!financial}><Input disabled={!financial} type="date" value={dateOnly(form.paymentDate)} onChange={(event) => set('paymentDate', event.target.value)} /></Field><Field label="Valor pago" disabled={!financial}><Input disabled={!financial} {...money('paidValueCents')} placeholder="0,00" /></Field><Field label="Chave PIX" disabled={!financial}><Input disabled={!financial} value={String(form.pixKey ?? '')} onChange={(event) => set('pixKey', event.target.value)} /></Field><Field label="Tipo chave" disabled={!financial}><Input disabled={!financial} value={String(form.pixKeyType ?? '')} onChange={(event) => set('pixKeyType', event.target.value)} /></Field><Field label="Banco" disabled={!financial}><Input disabled={!financial} value={String(form.bank ?? '')} onChange={(event) => set('bank', event.target.value)} /></Field><Field label="Titular" disabled={!financial}><Input disabled={!financial} value={String(form.accountHolder ?? '')} onChange={(event) => set('accountHolder', event.target.value)} /></Field></div></Section>
      <Section icon={Wrench} title="Resumo técnico no Jira"><div className="grid gap-3"><Field label="PROBLEMA IDENTIFICADO"><textarea value={String(form.identifiedProblem ?? '')} onChange={(event) => set('identifiedProblem', event.target.value)} rows={3} className="field min-h-20" /></Field><Field label="TESTES FEITOS"><textarea value={String(form.testsPerformed ?? '')} onChange={(event) => set('testsPerformed', event.target.value)} rows={3} className="field min-h-20" /></Field><Field label="PEÇA A SER TROCADA"><textarea value={String(form.partToReplace ?? '')} onChange={(event) => set('partToReplace', event.target.value)} rows={3} className="field min-h-20" /></Field></div></Section>
      <Field label="Descrição do atendimento"><textarea value={String(form.description ?? '')} onChange={(event) => set('description', event.target.value)} rows={4} className="field min-h-24" placeholder="Problema, serviço, pendências e instruções." /></Field>
      <div className="flex flex-wrap items-center gap-3 border-t border-border pt-4"><Button type="button" onClick={() => void save()} disabled={saving}>{saving ? <Loader2 className="animate-spin" /> : <Save />} Salvar operação</Button>{financial && <Button type="button" variant="outline" className="border-emerald-400/30 text-emerald-300" onClick={() => void save(false, true)} disabled={saving}><CheckCircle2 /> Confirmar pagamento e arquivar</Button>}{message && <p role="status" className="text-sm text-muted-foreground">{message}</p>}</div></div>}</DialogContent></Dialog>;
}
function Field({ label, children, disabled }: { label: string; children: React.ReactNode; disabled?: boolean }) { return <label className={disabled ? 'opacity-50' : ''}><span className="mb-1.5 block text-xs font-semibold text-muted-foreground">{label}</span>{children}</label>; }
function Section({ icon: Icon, title, children }: { icon: typeof Store; title: string; children: React.ReactNode }) { return <section className="rounded-xl border border-border p-4"><h3 className="mb-4 flex items-center gap-2 text-sm font-bold"><Icon className="size-4 text-primary" />{title}</h3>{children}</section>; }
function dateField(value: Form[string]) { if (typeof value !== 'string' || !value) return ''; const date = new Date(value); if (Number.isNaN(date.getTime())) return ''; const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); }
function dateOnly(value: Form[string]) { return typeof value === 'string' && value ? value.slice(0, 10) : ''; }
function toIso(value: Form[string]) { return typeof value === 'string' && value ? new Date(value).toISOString() : null; }
function moneyToCents(value: string) { const amount = Number(value.replace(',', '.')); return Number.isFinite(amount) && amount >= 0 ? Math.round(amount * 100) : null; }
function localStatus(value = '') { const status = value.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, ''); if (status === 'agendado') return 'scheduled'; if (status.includes('agendamento')) return 'scheduling'; if (status.includes('direcion')) return 'operational_preparation'; if (status.includes('campo') || status.includes('atendimento')) return 'in_service'; if (status.includes('spare')) return 'awaiting_spare'; return 'triage'; }
